### ISSUE TITLE
Deployment over network?

### ISSUE THREAD

**Issue by RicardoMusch** [cpenv/cpenv#39]
Hey,

I am looking into deploying cpenv to a studio network but do I really need to install pipx everywhere for that or is there a way I can point machines to a network share to be able to run cpenv.exe?

**Comment by danbradham** [comment]
Pipx is just the recommended method of installing cpenv. On a machine level it provides isolation from your system install of python which is ideal if you're only trying to use it as a CLI tool and not a library. A standard pip install also works.

You can absolutely put cpenv, or any python CLI tool for that matter, on a network share. I would recommend pip installing it into a virtual environment on your network share in that case. Then you could move the cpenv executable into a folder that you add to your users' PATH environment variable. Here's what that could look like via Powershell on windows.

```
> cd \\network_share\tools
> mkdir cpenv
> cd cpenv
> py -m venv python
> .\python\Scripts\Activate.ps1
> py -m pip install cpenv
> move .\python\Scripts\cpenv.exe cpenv.exe
```
Now you could add `\\network_share\tools\cpenv` to your users PATH variable to expose the tool for them.

If you have users on multiple operating systems you would need to create one of these virtual environment deployments for each OS. So you might have `//network_share/tools/cpenv/win`, `//network_share/tools/cpenv/mac`, and linux `//network_share/tools/cpenv/linux` each with their own virtual environment and cpenv executable.

**Comment by RicardoMusch** [comment]
Awesome, that works! :)
