### ISSUE TITLE
Warning messages in Linux subshell 

### ISSUE THREAD

**Issue by fabiangeisler** [cpenv/cpenv#58]
When I activate an environment with `cpenv activate`, I get these 2 error messages at the end:
```
/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/bin/subshell.sh: line 3: $'\r': command not found
/home/fabian.geisler/.local/pipx/venvs/cpenv/lib64/python3.6/site-packages/cpenv/bin/subshell.sh: line 7: $'\r': command not found
```
Note: The created subshell itself works fine! 

## Solution
These errors pop up because the `subshell.sh` partly contains windows line endings (`\r\n`) which bash is very picky about. Converting the script to Linux line endings (`\n`) fixes the issue. 

## Hint
To prevent this issue, I like to track a `.gitattributes` file in my repositories with this content:
```
# Default line ending behavior, in case people don't have core.autocrlf set.
* text=auto

# Files that will always have CRLF line endings on checkout.
# Windows command files
*.bat text eol=crlf
*.cmd text eol=crlf

# Files that will always have LF line endings on checkout.
# Linux command files
*.sh text eol=lf
*.env text eol=lf
```
This will make sure that common shell files get the correct line endings no matter the operating system you develop on.

**Comment by danbradham** [comment]
Nice, thanks for the details. Would you be able to make a PR?
